### PR TITLE
enabled tests by Django to workflows

### PR DESCRIPTION
**Pull request by lambdakilo**

### CODE REVIEW

**Review by VirtualAkseli — APPROVED** [review]
Good that you got this figured out!

**Comment by tapanih** [comment]
Looks good but creating a .env file seems unnecessary as it is not used anywhere.

**Comment by lambdakilo** [comment]
> Looks good but creating a .env file seems unnecessary as it is not used anywhere.

step Run Migrations warns about not finding the .env file. Should we just not create the .env file then?

**Comment by tapanih** [comment]
You have set the environmental variables elsewhere (because it works). The warning comes from dotenv library that is only used for local development environment (postgres installed on your computer)

**Comment by vuorenkoski** [comment]
ok, my 2h of wrestling with this one. It seems that makemigrations needs to be "makemigrations WebCLI". I removed database configuration from settings.py, but it is now yml file. Not sure which one is more logical place for that.

**Review by vuorenkoski — APPROVED** [review]

**Comment by tapanih** [comment]
Looks good to me.

**Pull request merged**
