### PR TITLE
Listing algorithms by type

### PR DESCRIPTION
**Pull request by VirtualAkseli**
## Description
- Listing by molecule and algorithm type works, narrowing the selection down to distinct molecules / algorithm type is not yet implemented.

## How to test:
**views.py**, **models.py** and **urls.py** have been changed, be wary if you have local changes to those.

- [ ] Add algorithm type
- [ ] Add molecule type
- [ ] Make a few algorithms with different combinations of the above
- [ ] Arrange the listing acordingly
- [ ] Observe results

Pencil_bloke

### CODE REVIEW

**Comment by lambdakilo** [comment]
Action:
1. add algo type A and B
2. add one molecule C
3. add two public algorithms from types A & B both on molecule C
4. Go to home page

Expected: Filter results by molecule drop downs one molecule to sort by
Actual: Filter results by molecule drop downs two molecules to sort by (both C)

Expected: Filter results by algorithm A sorts the results by algo A and sorting by B is still an option in the drop down.
Actual: Filter results by algorithm A reloads the page and hides the sorting option B.

also there is one conflicting file tho it didn't crash the application with the commit's version

If these two bugs are not bugs but rather features yet to be implemented this commit seems more than fine and ready to be merged

**Comment by VirtualAkseli** [comment]
> Action:
> 
>     1. add algo type A and B
> 
>     2. add one molecule C
> 
>     3. add two public algorithms from types A & B both on molecule C
> 
>     4. Go to home page
> 
> 
> Expected: Filter results by molecule drop downs one molecule to sort by
> Actual: Filter results by molecule drop downs two molecules to sort by (both C)
> 
> Expected: Filter results by algorithm A sorts the results by algo A and sorting by B is still an option in the drop down.
> Actual: Filter results by algorithm A reloads the page and hides the sorting option B.
> 
> also there is one conflicting file tho it didn't crash the application with the commit's version
> 
> If these two bugs are not bugs but rather features yet to be implemented this commit seems more than fine and ready to be merged

Yes, these faults are known. They are not bugs, just features that need to be implemented, since the current functions act a little dumb.

**Comment by lambdakilo** [comment]
fixed the conflict by choosing imports from the current commit
everything else looks good - merging

**Comment by lambdakilo** [comment]
also added the add_metrics to the urls.py

**Pull request merged**
