### PR TITLE
UI rework with Bootstrap

### PR DESCRIPTION
**Pull request by tapanih**
Description:
A quick sketch for a new UI with Bootstrap that has a navigation bar for easier and faster navigation between pages.

How to test:
Check all pages and forms.

### CODE REVIEW

**Comment by lambdakilo** [comment]
image
No module named bootstrap4 even after doing
`sudo docker-compose down`
`sudo docker-compose run web python manage.py  makemigrations`
`sudo docker-compose run web python manage.py migrate`
`sudo docker-compose up`

**Comment by VirtualAkseli** [comment]
Yeah, I'm also checking this out. Got the same errors.

**Comment by VirtualAkseli** [comment]
> image
> No module named bootstrap4 even after doing
> `sudo docker-compose down`
> `sudo docker-compose run web python manage.py makemigrations`
> `sudo docker-compose run web python manage.py migrate`
> `sudo docker-compose up`

I got it working locally with `python -m pip install bootstrap4
`

**Comment by lambdakilo** [comment]
> > image
> > No module named bootstrap4 even after doing
> > `sudo docker-compose down`
> > `sudo docker-compose run web python manage.py makemigrations`
> > `sudo docker-compose run web python manage.py migrate`
> > `sudo docker-compose up`
> 
> I got it working locally with `python -m pip install bootstrap4 `

This has to be implemened somehow to the docker as well

**Comment by tapanih** [comment]
You have to rebuild images because of the new dependencies with `sudo docker-compose up --build`. I don't know how to make this automatic at the moment. Sharing venv folder would be flaky because of Python version differencies.

**Comment by tapanih** [comment]
> > image
> > No module named bootstrap4 even after doing
> > `sudo docker-compose down`
> > `sudo docker-compose run web python manage.py makemigrations`
> > `sudo docker-compose run web python manage.py migrate`
> > `sudo docker-compose up`
> 
> I got it working locally with `python -m pip install bootstrap4 `

Did `pip install -r requirements.txt` not work?

**Comment by lambdakilo** [comment]
all pages and forms seem to work
updating the README building instructions

**Pull request merged**
